os:
 - linux
 - osx
osx_image: xcode7.1
sudo: false
language: c
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- curl -sSL https://get.haskellstack.org/ | sh

script:
- make
- cd test
- stack setup
- stack test

