script:
 - make
 - ls
 - ./fsatrace - -- cp /bin/ls /tmp/foo
 - ./fsatrace - -- mv /tmp/foo /tmp/bar
 - ./fsatrace - -- rm /tmp/bar
 - ./fsatrace - -- cc -D_GNU_SOURCE -D_BSD_SOURCE=1 -std=c99 -Wall -O3 fsatraceunix.c -o /tmp/fsatrace 
