script:
 - make
 - ls
 - ./fsatrace - -- cp /bin/ls /tmp/foo
 - ./fsatrace - -- mv /tmp/foo /tmp/bar
 - ./fsatrace - -- rm /tmp/bar
 - ./fsatrace - -- cc -c fsatrace.c -o /tmp/fsatrace.o
 - ./fsatrace out -- cc -c fsatrace.c -o /tmp/fsatrace.o
 - cat out
 - echo foo > out
 - cat out