os:
 - linux
 - osx
osx_image: xcode8.3
sudo: false
language: c
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl -sSL -o stack.tgz https://www.stackage.org/stack/linux-x86_64-static; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -sSL -o stack.tgz https://www.stackage.org/stack/osx-x86_64; fi
- tar xvfz stack.tgz
- cp stack-*/stack ~/.local/bin

script:
- make
- cd test
- stack setup
- stack test

