os:
 - linux
 - osx
osx_image: xcode7
script:
 - make
 - ./fsatrace - -- cp /bin/ls /tmp/foo
 - ./fsatrace - -- mv /tmp/foo /tmp/bar
 - ./fsatrace - -- rm /tmp/bar
 - ./fsatrace - -- sh -c "cp /bin/ls /tmp/foo && mv /tmp/foo /tmp/bar && rm /tmp/bar"
 - ./fsatrace - -- cc -c -D_GNU_SOURCE -D_BSD_SOURCE=1 -std=c99 -Wall -O3 fsatrace.c -o /tmp/fsatrace.o
