os:
 - linux
 - osx
osx_image: xcode7
language: c
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl -O -L https://github.com/commercialhaskell/stack/releases/download/v0.1.8.0/stack-0.1.8.0-linux-x86_64.tar.gz; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -O -L https://github.com/commercialhaskell/stack/releases/download/v0.1.8.0/stack-0.1.8.0-osx-x86_64.tar.gz; fi
- tar xvfz stack*
- cp stack-*/stack ~/.local/bin

script:
- env
- uname -a
- make
- otool -L fsatrace
- otool -L fsatrace.so
- cd test
- stack setup
- stack test --no-run-tests
- sudo dtruss -f .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/fsatrace-test/fsatrace-test

