platform: 
- x64

install:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- curl -omake.exe -L --insecure ftp://ftp.equation.com/make/64/make.exe
- 7z x stack.zip stack.exe
- stack setup --arch=x86_64 > nul
- stack setup --arch=i386 > nul

build: no

test_script:
- make htest
